# Generated by Django 3.2.6 on 2021-08-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
