# Generated by Django 3.2.6 on 2021-09-04 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='date_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
